# Generated by Django 4.2.5 on 2023-09-27 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot_machine_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spinresult',
            name='player',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='SpinResult',
        ),
    ]
