# Generated by Django 4.2.5 on 2023-09-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('UID', models.IntegerField(db_column='UID', primary_key=True, serialize=False)),
                ('AUTH_ID', models.IntegerField(db_column='AUTH_ID', default=3)),
                ('PASSWORD', models.CharField(db_column='PASSWORD', max_length=30)),
                ('NICK', models.CharField(db_column='NICK', max_length=30)),
                ('EMAIL', models.CharField(db_column='EMAIL', max_length=128)),
                ('MONEY', models.IntegerField(db_column='MONEY', default=1000000)),
                ('LOGIN_ID', models.CharField(db_column='LOGIN_ID', max_length=32)),
            ],
            options={
                'db_table': 'userInfo',
                'managed': False,
            },
        ),
    ]
